name: nancy

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/nancy.yml'
      - 'go.mod'
      - 'go.sum'

concurrency:
  group: nancy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.18.1

jobs:
  nancy:
    name: nancy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Caching dependency
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: WriteGoList
        run: go list -json -m all > go.list

      - name: Scan
        uses: sonatype-nexus-community/nancy-github-action@v1.0.2
