name: trivy scans

on:
  push:
    branches:
      - main
      - ampere-test
  pull_request:
    paths:
      - '.github/workflows/trivy-scans.yml'
      - '.trivyignore'

env:
  GO_VERSION: '1.19.6'
  IMAGE_TAG: ${{ github.run_id }}

concurrency:
  group: trivy-scans-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  trivy-fs-scan:
    # Use 20.04.5 until https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16450 is resolved
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run trivy filesystem scan
        uses: aquasecurity/trivy-action@0.9.2
        with:
          scan-type: 'fs'
          scan-ref: '.'
          skip-dirs: 'deployments,examples,instrumentation/packaging,internal/buildscripts/packaging,tests'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

  trivy-image-scan:
    # Use 20.04.5 until https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16450 is resolved
    runs-on: ${{ matrix.RUNNER }}
    strategy:
      matrix:
        include:
          - RUNNER: ubuntu-20.04
            ARCH: amd64
          - RUNNER: ampere
            ARCH: arm64
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: '**/go.sum'
      - uses: actions/cache@v3
        with:
          path: .cache/buildx/agent-bundle-${{ matrix.ARCH }}
          key: agent-bundle-buildx-${{ matrix.ARCH }}-${{ hashFiles('pkg/signalfx-agent/bundle/**') }}
      - run: |
          make docker-otelcol ARCH=${{ matrix.ARCH }} IMAGE_TAG=${{ env.IMAGE_TAG }}
        env:
          DOCKER_BUILDKIT: '1'
      - name: Run trivy image scan
        uses: aquasecurity/trivy-action@0.9.2
        with:
          scan-type: 'image'
          image-ref: otelcol:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
